#!/usr/bin/env bash
# Sync environment variables from apps/edge/.dev.vars to apps/mobile/.env
# This ensures a single source of truth for API keys

set -e

# Determine script directory and project root
SCRIPT_DIR="$(cd "$(dirname "$0")"; pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.."; pwd)"
EDGE_VARS="$ROOT_DIR/apps/edge/.dev.vars"
MOBILE_ENV="$ROOT_DIR/apps/mobile/.env"

echo "🔄 Syncing environment variables..."
echo ""

# Check if .dev.vars exists
if [ ! -f "$EDGE_VARS" ]; then
  echo "❌ $EDGE_VARS not found"
  echo ""
  echo "Please create it from the template:"
  echo "  cd apps/edge"
  echo "  cp .dev.vars.example .dev.vars"
  echo "  # Then edit .dev.vars with your actual API keys"
  echo ""
  exit 1
fi

# Extract ElevenLabs key from .dev.vars (simple KEY=VALUE parse)
# Handles both with and without quotes
ELEVEN_LINE="$(grep '^ELEVENLABS_API_KEY=' "$EDGE_VARS" || true)"

if [ -z "$ELEVEN_LINE" ]; then
  echo "⚠️  ELEVENLABS_API_KEY not found in $EDGE_VARS"
  echo "   Voice features will be disabled"
  echo ""
  ELEVEN_VALUE=""
  VOICE_ENABLED="false"
else
  # Extract value after = and remove any surrounding quotes
  ELEVEN_VALUE="${ELEVEN_LINE#ELEVENLABS_API_KEY=}"
  ELEVEN_VALUE="${ELEVEN_VALUE%\"}"
  ELEVEN_VALUE="${ELEVEN_VALUE#\"}"
  ELEVEN_VALUE="${ELEVEN_VALUE%\'}"
  ELEVEN_VALUE="${ELEVEN_VALUE#\'}"
  
  if [ -z "$ELEVEN_VALUE" ] || [ "$ELEVEN_VALUE" = "your-elevenlabs-api-key-here" ]; then
    echo "⚠️  ELEVENLABS_API_KEY is not set or is placeholder value"
    echo "   Voice features will be disabled"
    echo ""
    ELEVEN_VALUE=""
    VOICE_ENABLED="false"
  else
    echo "✅ Found ElevenLabs API key (${#ELEVEN_VALUE} characters)"
    VOICE_ENABLED="true"
  fi
fi

# Extract ELEVENLABS_MODE from .dev.vars
MODE_LINE="$(grep '^ELEVENLABS_MODE=' "$EDGE_VARS" || true)"

if [ -z "$MODE_LINE" ]; then
  # Default to 'mock' for safety (no API charges during dev)
  ELEVEN_MODE="mock"
  echo "⚠️  ELEVENLABS_MODE not found in $EDGE_VARS, defaulting to 'mock'"
else
  # Extract value after = and remove any surrounding quotes/whitespace/comments
  ELEVEN_MODE="${MODE_LINE#ELEVENLABS_MODE=}"
  # Strip inline comments (everything after #)
  ELEVEN_MODE="${ELEVEN_MODE%%#*}"
  # Remove quotes
  ELEVEN_MODE="${ELEVEN_MODE%\"}"
  ELEVEN_MODE="${ELEVEN_MODE#\"}"
  ELEVEN_MODE="${ELEVEN_MODE%\'}"
  ELEVEN_MODE="${ELEVEN_MODE#\'}"
  # Trim whitespace
  ELEVEN_MODE="$(echo "$ELEVEN_MODE" | xargs)"
  
  # Validate mode is 'mock' or 'live'
  if [ "$ELEVEN_MODE" != "mock" ] && [ "$ELEVEN_MODE" != "live" ]; then
    echo "⚠️  Invalid ELEVENLABS_MODE='$ELEVEN_MODE' (must be 'mock' or 'live'), defaulting to 'mock'"
    ELEVEN_MODE="mock"
  fi
fi

# Set VOICE_MOCK based on mode
if [ "$ELEVEN_MODE" = "mock" ]; then
  VOICE_MOCK="true"
  VOICE_MODE_DISPLAY="MOCK"
  VOICE_MODE_EMOJI="🎭"
else
  VOICE_MOCK="false"
  VOICE_MODE_DISPLAY="LIVE"
  VOICE_MODE_EMOJI="📡"
fi

# Generate mobile .env file
cat > "$MOBILE_ENV" <<EOF
# ============================================
# AUTOGENERATED by scripts/sync-env.sh
# DO NOT EDIT THIS FILE DIRECTLY
# DO NOT COMMIT THIS FILE
# ============================================
#
# Source of truth: apps/edge/.dev.vars
# To update: edit .dev.vars and run: npm run sync-env
#
# Generated: $(date)

# ========================================
# VOICE SYSTEM CONFIGURATION
# ========================================

# Voice system enabled (derived from ElevenLabs key presence)
EXPO_PUBLIC_VOICE_ENABLED=${VOICE_ENABLED}

# Voice engine to use
EXPO_PUBLIC_VOICE_ENGINE=elevenlabs

# ElevenLabs Configuration
EXPO_PUBLIC_ELEVENLABS_ENABLED=${VOICE_ENABLED}

# Mock mode (true = no API calls, false = real audio)
EXPO_PUBLIC_VOICE_MOCK=${VOICE_MOCK}
EOF

# Add API key only if it's set
if [ -n "$ELEVEN_VALUE" ]; then
  echo "EXPO_PUBLIC_ELEVENLABS_API_KEY=${ELEVEN_VALUE}" >> "$MOBILE_ENV"
else
  echo "# EXPO_PUBLIC_ELEVENLABS_API_KEY not set (add ELEVENLABS_API_KEY to .dev.vars)" >> "$MOBILE_ENV"
fi

# Add voice settings
cat >> "$MOBILE_ENV" <<EOF

# Voice Settings (customize as needed)
EXPO_PUBLIC_VOICE_AUTOPLAY=false
EXPO_PUBLIC_VOICE_VOLUME=0.7
EXPO_PUBLIC_VOICE_PRESET=colonel-neutral
EXPO_PUBLIC_VOICE_SFX=true

# ========================================
# API CONFIGURATION
# ========================================

# Backend API URL (defaults to localhost:8787 in dev)
# EXPO_PUBLIC_API_URL=http://localhost:8787

# Session ID prefix
# EXPO_PUBLIC_SESSION_ID_PREFIX=chatlali

# App version
# EXPO_PUBLIC_APP_VERSION=1.0.0
EOF

echo ""
echo "✅ Synced environment variables:"
echo "   Source: apps/edge/.dev.vars"
echo "   Target: apps/mobile/.env"
echo ""

if [ "$VOICE_ENABLED" = "true" ]; then
  echo "🎤 Voice features: ENABLED"
  echo "   Voice box will appear in the UI"
  echo ""
  echo "${VOICE_MODE_EMOJI} Voice mode: ${VOICE_MODE_DISPLAY}"
  if [ "$ELEVEN_MODE" = "mock" ]; then
    echo "   Zero API calls, zero cost (perfect for development)"
    echo "   To switch to real audio: set ELEVENLABS_MODE=live in .dev.vars"
  else
    echo "   ⚠️  Using real ElevenLabs API (will incur charges)"
    echo "   To save costs: set ELEVENLABS_MODE=mock in .dev.vars"
  fi
else
  echo "🔇 Voice features: DISABLED"
  echo "   To enable: add ELEVENLABS_API_KEY to apps/edge/.dev.vars"
fi

echo ""
echo "Done! 🎉"
